add checks to linux builder

diff --git a/linux/i2pd/i2pd b/linux/i2pd/i2pd
--- a/linux/i2pd/i2pd
+++ b/linux/i2pd/i2pd
@@ -8,6 +8,12 @@
 
 arch=$(uname -m)
 
+screenfind=$(which screen)
+if [ -z $curlfind ]; then
+        echo "Can't find 'screen' installed. That script needs it!";
+        exit 1;
+fi
+
 if [ $arch == "x86_64" ]
 	screen -Adm -S i2pd ./i2pd-x86_64 --datadir=.
 else
